### ISSUE TITLE
Github Enterprise support

### ISSUE THREAD

**Issue by johntdyer** [donnemartin/gitsome#3]
Any plans to support GH enterprise? I know the github3 package supports it.

**Comment by donnemartin** [comment]
Thanks for the suggestion, I'll check it out and post back.

**Comment by aaronkorver** [comment]
Another +1 for GH Enterprise

**Comment by bradparks** [comment]
Great project, and great idea.... 👍

**Comment by donnemartin** [comment]
Thanks for the feedback everyone.  It seems this is do-able with the [enterprise_login method](https://github.com/donnemartin/gitsome/blob/47322f4fc1daa9561b497a7d39c4bdd6037e409e/gitsome/lib/github3/api.py#L68-L98).

Currently `gitsome` just does the standard [login](https://github.com/donnemartin/gitsome/blob/47322f4fc1daa9561b497a7d39c4bdd6037e409e/gitsome/lib/github3/api.py#L41-L65).

However, I don't have an enterprise account to test on.  I could work on putting the fix on a branch, would anyone be able to help test it?  I could provide install instructions.

**Comment by johntdyer** [comment]
I can give it a shot

**Comment by donnemartin** [comment]
@johntdyer thanks!  Just heard from GitHub, they hooked up an Enterprise account to help with the effort.  I'll see if I can free up over the next few days and support this feature.

**Comment by bradparks** [comment]
Sweet! I'll test it out as well... Thanks!

Brad

**Comment by donnemartin** [comment]
Quick update: I have GitHub Enterprise now up and running and I'm able to login with `gitsome`.

I'll do some more testing and polish up the code before submitting a PR.

**Comment by donnemartin** [comment]
PR merged to master: https://github.com/donnemartin/gitsome/pull/36, it has **not** yet been pushed to PyPI, pending further testing.

@johntdyer @bradparks do you mind testing to verify it works on your end?  Since the changes are not yet on PyPI, here are two options discussed in the `README` to get it.

You might need to use `sudo` or `pip3`, check out the install section instructions for more details.

### Option 1

...

You can also install the latest `gitsome` from GitHub source which can contain changes not yet pushed to PyPI:

    $ pip install git+https://github.com/donnemartin/gitsome.git

...

### Option 2

Check out the [Developer Installation](https://github.com/donnemartin/gitsome#developer-installation) section.

**Comment by donnemartin** [comment]
### gh configure

Configure `gitsome`.

Attempts to authenticate the user and to set up the user's news feed.

If `gitsome` has not yet been configured, calling a `gh` command that requires authentication will automatically invoke the `configure` command.

Usage/Example(s):

    $ gh configure

For GitHub Enterprise users, run with the `-e/--enterprise` flag:

    $ gh configure -e

#### GitHub Enterprise

GitHub Enterprise users will be asked to enter the GitHub Enterprise url and whether they want to verify SSL certificates.

**Comment by donnemartin** [comment]
Associated PRs:

* https://github.com/donnemartin/gitsome/pull/36
* https://github.com/donnemartin/gitsome/pull/42
* https://github.com/donnemartin/gitsome/pull/43

Released with 0.6.0: https://github.com/donnemartin/gitsome/issues/55
